[project]
name = "django-tutorial"
version = "0.1.0"
description = "Django Tutorial"
authors = [
    {name = "Zoltan", email = ""},
]
dependencies = [
    "django>=5.0.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
package-type = "application"
